spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:100.x.x.x}:${DB_PORT:5432}/${DB_NAME:telemetriadb}
    username: ${DB_USER:admin}
    password: ${DB_PASS:secret}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  grafana:
    dashboard-url: ${GRAFANA_DASHBOARD_URL:http://localhost:3000/grafana/public-dashboards/8fe987f683794be4aa6898cd23e5f988}
  internal:
    auth-token: ${INTERNAL_AUTH_TOKEN:change-me}

server:
  port: 8080