services:
  grafana:
    image: grafana/grafana:12.1.0
    container_name: webhardmon-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_DOMAIN: localhost
      GF_SERVER_ROOT_URL: http://localhost:3000/
      GF_SERVER_SERVE_FROM_SUB_PATH: "false"

      GF_AUTH_PROXY_ENABLED: "false"
      GF_AUTH_BASIC_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"

      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_USERS_ALLOW_SIGN_UP: "false"

    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning

  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: webhardmon-victoriametrics
    restart: unless-stopped
    ports:
      - "8428:8428"

volumes:
  grafana_data: